name: Selenium Test1

on:
  push:
    branches: [ "main" ]

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 7
      uses: actions/setup-java@v3
      with:
        java-version: '7'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
